### ISSUE TITLE
Area selection rendering is problematic

### ISSUE THREAD

**Issue by alexbooker** [jomo/imgur-screenshot#32]
I noticed that the area selection is rendering funny on my computer.

I am running Ubuntu 14.10.

**Comment by jomo** [comment]
That's scrot's fault. Try using an alternative such as [Roger/escrotum](https://github.com/Roger/escrotum).

Then include this in your config:
```bash
screenshot_select_command="escrotum -s %img"
screenshot_window_command="escrotum %img"
```

**Comment by alexbooker** [comment]
I will look into this in a moment. Thank you.

**Comment by alexbooker** [comment]
OH: I installed escrotum and everything works **much** better. I highly recommend it to anyone reading this.

**Comment by Brottweiler** [comment]
I just saw https://github.com/jomo/imgur-screenshot/issues/75, and since it's related I want to add my thoughts.

I switched from scrot to escrotum, but after that I switched to https://github.com/naelstrof/maim which uses https://github.com/naelstrof/slop, but that's just my personal preference. Choose which one suits you best.

**Comment by qwemaze** [comment]
How does one can edit a config?

**Comment by qwemaze** [comment]
Tried `imgur-screenshot -i screenshot_window_command="maim -i$(xdotool getactivewindow) %img"` but it just takes a selection.

**Comment by jomo** [comment]
https://github.com/jomo/imgur-screenshot/wiki/Config
