### ISSUE TITLE
Customize how link is copied

### ISSUE THREAD

**Issue by CestDiego** [jomo/imgur-screenshot#37]
I'd like to use screenshots from imgur into some chats like gitter, slack, and even org-mode for emacs, in the latter it's not so much of a trouble as one can do `C-c C-l` and it captured the clipboard link. But it would be awesome if we could do sth like `imgur-screenshot --wrapper "[![alt_text](%s)](%s)]" ` and that would give a link in the clipboard as this:
`[![alt_text](https://i.imgur.com/7qYlP3Z.png)](https://i.imgur.com/7qYlP3Z.png)`
so that we could paste it directly in github issues too like this:
[![alt_text](https://i.imgur.com/7qYlP3Z.png)](https://i.imgur.com/7qYlP3Z.png)

**Comment by jomo** [comment]
Hmm, I think this wouldn't be used by a lot of people (unless I hear otherwise).

This project started as a really simple 40 line script and now it's already more than 10x the size, I think I'm only going to accept feature requests that are requested a lot (or would probably be used by many).

If you really  want this to be added, feel free to fork!

I will re-open this issue if some more people ask for it to be added.
