### ISSUE TITLE
Image Editor Always Opens in Background

### ISSUE THREAD

**Issue by hex3r** [jomo/imgur-screenshot#89]
I was wondering if there is a way to make the editor I pass as -i argument to always open in the foreground (on top of other windows). Right now it just hangs in the background until I manually find it.

**Comment by jomo** [comment]
The script just runs whatever command you configured. Many operating systems come with an `open` or `xdg-open` command that might help. Perhaps the editor you use has some flags to force opening in foreground? Otherwise you could  try messing with `xdotool` or similar.

However, this is not in the scope of this script.

**Comment by hex3r** [comment]
I figured this out after a while. Had to run the script with `-i 'open -W -a Editor %img'` parameters.
